spring.application.name=CommunityBudget
server.port=${SERVER_PORT}
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/community_budget?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
springdoc.swagger-ui.urls[0].name=Users API
springdoc.swagger-ui.urls[0].url=/webdoc/users-api.yaml
springdoc.swagger-ui.urls[1].name=Groups API
springdoc.swagger-ui.urls[1].url=/webdoc/groups-api.yaml
springdoc.swagger-ui.urls[2].name=Expenses API
springdoc.swagger-ui.urls[2].url=/webdoc/expenses-api.yaml
server.error.include-binding-errors=always
server.error.include-message=always
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration.ms=${JWT_EXPIRATION_MS}
jwt.refresh.expiration.ms=${JWT_REFRESH_EXPIRATION_MS}
mail.from=${MAIL_FROM:noreply@communitybudget.local}
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USER:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:false}
mail.reset-password=${URL_RESET_PASSWORD}
