spring.application.name=CommunityBudget
server.port=${SERVER_PORT}
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/community_budget
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
springdoc.swagger-ui.url=/webdoc/openapi.yaml
server.error.include-binding-errors=always
server.error.include-message=always